services:
  football_quiz_api:
    image: football_quiz_api:dev
    container_name: football_quiz_api
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3002:3001
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    environment:
      CACHE_HOST: redis
      CACHE_PORT: 6379
      CACHE_PASSWORD: ""
      DB_HOST: postgres
      DB_PORT: 5432
      PORT: 3001

  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6382:6379'
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:15.10-alpine3.20
    container_name: postgres_db
    restart: always
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    volumes:
      - postgres-data:/var/lib/postgresql/data

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt

volumes:
  postgres-data:
  redis-data:
